spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: vrkolur
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction:
          coordinator_class: jdbc
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB

api:
  prefix: /api/v1